FROM node:18 as build
WORKDIR /usr/src/app
ADD . .

FROM node:18-slim as running
WORKDIR /usr/src/app
HEALTHCHECK CMD node healthcheck
EXPOSE 3000

FROM build as build-dev
RUN npm ci

FROM running as development
COPY --from=build-dev /usr/src/app .
CMD ["npm", "run", "start:dev"]